common:
  app: geocoder-proxy
  shortname: geocoder # This ID is defined in .entur/project.yml and is shared with geocoder-photon
  team: team-ror
  ingress:
    enabled: true
    trafficType: public
  service:
    internalPort: 8080  # What TCP port the application listens on the pod, must match the port in the Dockerfile
  deployment:
    prometheus:
      enabled: true
      path: /metrics
      port: 8080
  container:
    image: <+artifacts.primary.image>  # The CD tool will replace this value with the actual image
    cpu: 0.3 # Adjust this to your application needs
    memory: 512 # Adjust this to your application needs, a java application might need more memory to start like 1024 or 2048 or +++
    probes:
      enabled: true
      spec:
        startupProbe:
          tcpSocket:
            port: 8080
          periodSeconds: 1
          timeoutSeconds: 1
          failureThreshold: 300
        readinessProbe:
          httpGet:
            path: /v2/autocomplete?text=zzzzz
            port: 8080
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          tcpSocket:
            port: 8080
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
  postgres: # sets up a postgres proxy so you can connect to your postgresql instance via localhost on the pod
    enabled: false
