[versions]
kotlin = "2.2.21"
ktor = "3.3.2"
jackson = "2.20.1"
logback = "1.5.20"
geotools = "33.2"
ktlint-gradle = "13.1.0"
osmosis = "0.49.2"
shadow = "9.2.2"

[libraries]
geotools-referencing = { module = "org.geotools:gt-referencing", version.ref = "geotools" }
geotools-main = { module = "org.geotools:gt-main", version.ref = "geotools" }
geotools-epsg-wkt = { module = "org.geotools:gt-epsg-wkt", version.ref = "geotools" }

jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-xml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }

osmosis_core = { module = "org.openstreetmap.osmosis:osmosis-core", version.ref = "osmosis" }
osmosis_pbf = { module = "org.openstreetmap.osmosis:osmosis-pbf", version.ref = "osmosis" }
osmosis_xml = { module = "org.openstreetmap.osmosis:osmosis-xml", version.ref = "osmosis" }

ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
ktor-server-metrics = { module = "io.ktor:ktor-server-metrics", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-serialization-jackson = { module = "io.ktor:ktor-serialization-jackson", version.ref = "ktor" }

logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

country-boundaries = { module = "de.westnordost:countryboundaries", version = "3.0.0" }

ktor-server-metrics-micrometer = { module = "io.ktor:ktor-server-metrics-micrometer", version.ref = "ktor" }
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version = "1.10.3" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }