common:
  env: prd
  replicas: 2
  ingress:
    host: geocoder-proxy.entur.io
  hpa:
    spec:
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 80
      maxReplicas: 10
      minReplicas: 2
