common:
  env: prd
  replicas: 2
  container:
    cpu: 1
    memory: 1536
  ingress:
    enabled: false
  hpa:
    spec:
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 80
      maxReplicas: 10
      minReplicas: 2
