common:
  app: geocoder-photon
  shortname: geocoder # This ID is defined in .entur/project.yml and is shared with geocoder-proxy
  team: team-ror
  ingress:
    enabled: true
    trafficType: public
  service:
    internalPort: 2322  # What TCP port the application listens on the pod, must match the port in the Dockerfile
  deployment:
    prometheus:
      enabled: true
      path: /metrics
      port: 2322
  container:
    image: <+artifacts.primary.image>  # The CD tool will replace this value with the actual image
    cpu: 0.3 # Adjust this to your application needs
    memory: 512 # Adjust this to your application needs, a java application might need more memory to start like 1024 or 2048 or +++
    probes:
      enabled: true
      spec:
        startupProbe:
          tcpSocket:
            port: 2322
          periodSeconds: 1
          timeoutSeconds: 1
          failureThreshold: 300
        readinessProbe:
          httpGet:
            path: /api?q=test&limit=1
            port: 2322
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /status
            port: 2322
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
  postgres: # sets up a postgres proxy so you can connect to your postgresql instance via localhost on the pod
    enabled: false
