#
# API Documentation Workflow
#
# Api specs end up at https://beta.developer.entur.no/apis/public
#

name: API Docs

on:
  push:
    paths:
      - 'proxy/docs/**'
      - 'proxy/src/main/resources/openapi.yml'
      - 'proxy/.spectral.yml'
      - '.github/workflows/api-docs.yml'
  pull_request:
    paths:
      - 'proxy/docs/**'
      - 'proxy/src/main/resources/openapi.yml'
      - 'proxy/.spectral.yml'
      - '.github/workflows/api-docs.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api-lint:
    uses: entur/gha-api/.github/workflows/lint.yml@v4
    secrets: inherit
    with:
      spec: proxy/src/main/resources/openapi.yml

  api-publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: api-lint
    uses: entur/gha-api/.github/workflows/publish.yml@v4
    secrets: inherit
    with:
      spec: proxy/src/main/resources/openapi.yml

  docs-publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: api-lint
    uses: entur/gha-docs/.github/workflows/publish.yml@v1
    secrets: inherit
    with:
      project: geocoder
      directory: proxy/docs
