name: Proxy - Build and deploy

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '.entur/**'
      - 'converter/**'
      - 'helm/**'
      - 'photon/**'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '.entur/**'
      - 'converter/**'
      - 'helm/**'
      - 'photon/**'
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: 'Environment to deploy to (dev, tst, prd)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - tst
          - prd
      image_tag:
        description: 'Tag to deploy'
        required: false
        default: 'latest'
        type: string

run-name: ${{ github.event_name == 'workflow_dispatch' && format('Deploy to {0} (tag={1})', inputs.deploy_environment, inputs.image_tag) || (github.event_name == 'pull_request' && github.event.pull_request.title) || github.event.head_commit.message }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    uses: entur/gha-docker/.github/workflows/lint.yml@v1
    with:
      dockerfile: proxy/Dockerfile
      ignore: "DL3018,DL3059"

  build-push:
    name: Proxy
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image_tag: ${{ steps.build-push.outputs.image_tag }}

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: liberica
          java-version: 21
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew --no-daemon build

      - name: Build and Push
        id: build-push
        uses: ./.github/actions/docker-build-push
        with:
          image_name: geocoder-proxy
          context: proxy
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          workload_identity_provider: ${{ vars.CI_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.CI_SERVICE_ACCOUNT }}

  scan:
    name: Scan
    if: |
      !cancelled() &&
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main' &&
      needs.build-push.result == 'success'
    needs: [ build-push ]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v5

      - name: Security Scan
        uses: ./.github/actions/docker-scan
        with:
          image: "geocoder-proxy:${{ needs.build-push.outputs.image_tag }}"
          workload_identity_provider: ${{ vars.CI_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.CI_SERVICE_ACCOUNT }}

  deploy-dev:
    name: Dev
    if: |
      !cancelled() &&
      ((github.event_name == 'push' && needs.build-push.result == 'success') || (github.event_name == 'workflow_dispatch' && inputs.deploy_environment == 'dev')) &&
      github.ref == 'refs/heads/main'
    needs: build-push
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1
    with:
      environment: dev
      image: "geocoder-proxy:${{ needs.build-push.outputs.image_tag }}"
      chart: helm/geocoder-proxy
      namespace: geocoder
      release_name: geocoder-proxy
    secrets: inherit

  acceptance-tests-dev:
    name: Dev Tests
    if: needs.deploy-dev.result == 'success'
    needs: deploy-dev
    uses: "./.github/workflows/acceptance-tests.yml"
    with:
      environment: dev

  deploy-tst:
    name: Staging
    if: |
      !cancelled() &&
      github.event_name == 'workflow_dispatch' &&
      github.ref == 'refs/heads/main' &&
      inputs.deploy_environment == 'tst'
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1
    with:
      environment: tst
      image: "geocoder-proxy:${{ inputs.image_tag }}"
      chart: helm/geocoder-proxy
      namespace: geocoder
      release_name: geocoder-proxy
    secrets: inherit

  acceptance-tests-tst:
    name: Staging Tests
    if: needs.deploy-tst.result == 'success'
    needs: deploy-tst
    uses: "./.github/workflows/acceptance-tests.yml"
    with:
      environment: tst

  deploy-prd:
    name: Prod
    if: |
      !cancelled() &&
      github.event_name == 'workflow_dispatch' &&
      github.ref == 'refs/heads/main' &&
      inputs.deploy_environment == 'prd'
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1
    with:
      environment: prd
      image: "geocoder-proxy:${{ inputs.image_tag }}"
      chart: helm/geocoder-proxy
      namespace: geocoder
      release_name: geocoder-proxy
    secrets: inherit

  acceptance-tests-prd:
    name: Prod Tests
    if: needs.deploy-prd.result == 'success'
    needs: deploy-prd
    uses: "./.github/workflows/acceptance-tests.yml"
    with:
      environment: prd

