name: Proxy - Build and deploy

on:
  push:
    paths-ignore:
      - '.entur/**'
  pull_request:
    paths-ignore:
      - '.entur/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: entur/gha-docker/.github/workflows/lint.yml@v1
    with:
      dockerfile: Dockerfile.proxy
      ignore: "DL3018,DL3059"

  build-push:
    needs: lint
    uses: "./.github/workflows/_build-push.yml"
    with:
      image_name: geocoder-proxy
      dockerfile: Dockerfile.proxy
      push: ${{ github.event_name != 'pull_request' }}
      do-gradle-build: true

  scan:
    if: |
      !cancelled() &&
      github.event_name != 'pull_request' &&
      needs.build-push.result == 'success'
    needs: [build-push]
    uses: "./.github/workflows/_docker-scan.yml"
    with:
      image: "geocoder-proxy:${{ needs.build-push.outputs.image_tag }}"

  deploy-dev:
    if: |
      !cancelled() &&
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main' &&
      needs.build-push.result == 'success'
    needs: build-push
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1
    with:
      environment: dev
      image: "geocoder-proxy:${{ needs.build-push.outputs.image_tag }}"
      chart: helm/geocoder-proxy
      namespace: geocoder
      release_name: geocoder-proxy
    secrets: inherit

  acceptance-tests-dev:
    if: needs.deploy-dev.result == 'success'
    needs: deploy-dev
    uses: "./.github/workflows/acceptance-tests.yml"
    with:
      environment: dev

  deploy-staging:
    if: |
      !cancelled() &&
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main' &&
      needs.build-push.result == 'success'
    needs: [build-push, deploy-dev]
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1
    with:
      environment: tst
      image: "geocoder-proxy:${{ needs.build-push.outputs.image_tag }}"
      chart: helm/geocoder-proxy
      namespace: geocoder
      release_name: geocoder-proxy
    secrets: inherit

  acceptance-tests-staging:
    if: needs.deploy-staging.result == 'success'
    needs: deploy-staging
    uses: "./.github/workflows/acceptance-tests.yml"
    with:
      environment: staging


