name: Proxy - Build and deploy

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '.entur/**'
      - 'converter/**'
      - 'helm/**'
      - 'photon/**'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '.entur/**'
      - 'converter/**'
      - 'helm/**'
      - 'photon/**'
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'Deploy to environment (NB! No review required!)'
        required: true
        default: 'ðŸš€ Dev'
        type: choice
        options:
          - 'ðŸš€ Dev'
          - 'ðŸš€ Staging'
          - 'ðŸš€ Prod'
      image_tag:
        description: 'Image tag to deploy'
        required: false
        default: 'latest'
        type: string

run-name: "Proxy: ${{ github.event_name == 'workflow_dispatch' && format('{0} (tag={1})', inputs.deploy_env, inputs.image_tag) || (github.event_name == 'pull_request' && github.event.pull_request.title) || github.event.head_commit.message }}"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-${{ inputs.deploy_env || 'none' }}"
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.vars.outputs.build }}
      dev: ${{ steps.vars.outputs.dev }}
      tst: ${{ steps.vars.outputs.tst }}
      prd: ${{ steps.vars.outputs.prd }}
    steps:
      - id: vars
        run: |
          # Determine what to build and deploy based on trigger
          if [ "${{ github.event_name }}" = "push" ] || [ "${{ github.event_name }}" = "pull_request" ]; then
            build=true
            if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref }}" = "refs/heads/main" ]; then
              dev=true
            fi
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            if [ "${{ inputs.deploy_env }}" = "ðŸš€ Dev" ]; then
              dev=true
            elif [ "${{ inputs.deploy_env }}" = "ðŸš€ Staging" ]; then
              tst=true
            elif [ "${{ inputs.deploy_env }}" = "ðŸš€ Prod" ]; then
              prd=true
            else
              echo "Error: Invalid deploy_env input (received: '${{ inputs.deploy_env }}')"
              exit 1
            fi
          fi
          echo "build=${build:-false}" >> $GITHUB_OUTPUT
          echo "dev=${dev:-false}" >> $GITHUB_OUTPUT
          echo "tst=${tst:-false}" >> $GITHUB_OUTPUT
          echo "prd=${prd:-false}" >> $GITHUB_OUTPUT

  lint:
    name: Lint
    if: needs.setup.outputs.build == 'true'
    needs: setup
    uses: entur/gha-docker/.github/workflows/lint.yml@v1
    with:
      dockerfile: proxy/Dockerfile
      ignore: "DL3018,DL3059"

  build-push:
    name: Proxy
    if: needs.setup.outputs.build == 'true'
    needs: [setup]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image_tag: ${{ steps.build-push.outputs.image_tag }}

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: liberica
          java-version: 21
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew --no-daemon build

      - name: Build and Push
        id: build-push
        uses: ./.github/actions/docker-build-push
        with:
          image_name: geocoder-proxy
          context: proxy
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          workload_identity_provider: ${{ vars.CI_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.CI_SERVICE_ACCOUNT }}

  scan:
    name: Scan
    if: |
      !cancelled() &&
      needs.setup.outputs.build == 'true' &&
      needs.build-push.result == 'success'
    needs: [setup, build-push]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v5

      - name: Security Scan
        uses: ./.github/actions/docker-scan
        with:
          image: "geocoder-proxy:${{ needs.build-push.outputs.image_tag }}"
          workload_identity_provider: ${{ vars.CI_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.CI_SERVICE_ACCOUNT }}

  # Helm deploy fails to handle 'latest' properly
  resolve-image-tag:
    name: Resolve image tag
    if: needs.setup.outputs.dev == 'true' || needs.setup.outputs.tst == 'true' ||needs.setup.outputs.prd == 'true'
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      resolved_tag: ${{ steps.resolve.outputs.resolved_tag }}
    steps:
      - uses: actions/checkout@v5

      - name: Resolve image tag
        id: resolve
        uses: ./.github/actions/resolve-image-tag
        with:
          image_name: geocoder-proxy
          image_tag: ${{ inputs.image_tag }}
          workload_identity_provider: ${{ vars.CI_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.CI_SERVICE_ACCOUNT }}

  deploy-dev:
    name: Dev
    if: |
      !cancelled() &&
      github.ref == 'refs/heads/main' &&
      needs.lint.result == 'success' &&
      needs.setup.outputs.dev == 'true' &&
      (needs.build-push.result == 'success' || needs.setup.outputs.build == 'false')
    needs: [setup, lint, build-push, resolve-image-tag]
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1
    with:
      environment: dev
      image: "geocoder-proxy:${{ needs.setup.outputs.build == 'true' && needs.build-push.outputs.image_tag || needs.resolve-image-tag.outputs.resolved_tag }}"
      chart: helm/geocoder-proxy
      namespace: geocoder
      release_name: geocoder-proxy
    secrets: inherit

  acceptance-tests-dev:
    name: Dev Tests
    if: needs.deploy-dev.result == 'success'
    needs: deploy-dev
    uses: "./.github/workflows/acceptance-tests.yml"
    with:
      environment: dev

  deploy-tst:
    name: Staging
    if: |
      !cancelled() &&
      github.ref == 'refs/heads/main' &&
      needs.setup.outputs.tst == 'true'
    needs: [setup, resolve-image-tag]
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1
    with:
      environment: tst
      image: "geocoder-proxy:${{ needs.resolve-image-tag.outputs.resolved_tag }}"
      chart: helm/geocoder-proxy
      namespace: geocoder
      release_name: geocoder-proxy
    secrets: inherit

  acceptance-tests-tst:
    name: Staging Tests
    if: needs.deploy-tst.result == 'success'
    needs: deploy-tst
    uses: "./.github/workflows/acceptance-tests.yml"
    with:
      environment: tst

  deploy-prd:
    name: Prod
    if: |
      !cancelled() &&
      github.ref == 'refs/heads/main' &&
      needs.setup.outputs.prd == 'true'
    needs: [setup, resolve-image-tag]
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1
    with:
      environment: prd
      image: "geocoder-proxy:${{ needs.resolve-image-tag.outputs.resolved_tag }}"
      chart: helm/geocoder-proxy
      namespace: geocoder
      release_name: geocoder-proxy
    secrets: inherit

  acceptance-tests-prd:
    name: Prod Tests
    if: needs.deploy-prd.result == 'success'
    needs: deploy-prd
    uses: "./.github/workflows/acceptance-tests.yml"
    with:
      environment: prd

