name: Proxy - Build and deploy

on:
  push:
    paths-ignore:
      - '.entur/**'
  pull_request:
    paths-ignore:
      - '.entur/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  proxy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Docker Lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.proxy

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: '21'
          cache: 'gradle'

      - name: Build everything
        run: ./gradlew --no-daemon build

      - name: Build and push Docker image
        id: build-push
        uses: ./.github/actions/build-push
        with:
          image_name: geocoder-proxy
          dockerfile: Dockerfile.proxy
          push: ${{ github.event_name != 'pull_request' }}
          service_account: ${{ vars.CI_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ vars.CI_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Scan
        if: github.event_name != 'pull_request'
        uses: ./.github/actions/docker-scan
        with:
          image_name: "${{ steps.build-push.outputs.image_name }}:${{ steps.build-push.outputs.image_tag }}"

  deploy-dev:
    if: |
      !cancelled() &&
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main' &&
      needs.build-push.result == 'success'
    needs: proxy
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1
    with:
      environment: dev
      image: ${{ needs.proxy.outputs.image_name }}:${{ needs.proxy.outputs.image_tag }}
      chart: helm/geocoder-proxy
      namespace: geocoder
      release_name: geocoder-proxy
    secrets: inherit

  deploy-tst:
    if: |
      !cancelled() &&
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main' &&
      needs.build-push.result == 'success'
    needs: [proxy, deploy-dev]
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1
    with:
      environment: tst
      image: ${{ needs.proxy.outputs.image_name }}:${{ needs.proxy.outputs.image_tag }}
      chart: helm/geocoder-proxy
      namespace: geocoder
      release_name: geocoder-proxy
    secrets: inherit


