name: Proxy - Build and deploy

on:
  push:
    paths-ignore:
      - '.entur/**'
  pull_request:
    paths-ignore:
      - '.entur/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: entur/gha-docker/.github/workflows/lint.yml@v1
    with:
      dockerfile: Dockerfile.proxy

  build:
    needs: lint
    uses: entur/gha-docker/.github/workflows/build.yml@v1
    with:
      dockerfile: Dockerfile.proxy
      image_name: geocoder-proxy

  push:
    if: ${{ github.event_name != 'pull_request' }}
    needs: build
    uses: entur/gha-docker/.github/workflows/push.yml@v1
    with:
      dockerfile: Dockerfile.proxy
      image_name: geocoder-proxy

  scan:
    needs: [build]
    uses: entur/gha-security/.github/workflows/docker-scan.yml@v2
    with:
      image_artifact: ${{ needs.build.outputs.image_artifact }}

  deploy-dev:
    if: ${{ github.event_name != 'pull_request' }}
    needs: push
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1
    with:
      environment: dev
      image: ${{ needs.push.outputs.image_name }}:${{ needs.push.outputs.image_tag}}
      chart: helm/geocoder-proxy
      namespace: geocoder
      release_name: geocoder-proxy
    secrets: inherit

  deploy-tst:
    if: ${{ github.event_name != 'pull_request' }}
    needs: [push,deploy-dev]
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1
    with:
      environment: tst
      image: ${{ needs.push.outputs.image_name }}:${{ needs.push.outputs.image_tag}}
      chart: helm/geocoder-proxy
      namespace: geocoder
      release_name: geocoder-proxy
    secrets: inherit


