name: Helm Deploy

on:
  push:

jobs:
  helm-deploy:
    uses: entur/gha-helm/.github/workflows/deploy.yml@v1
    with:
      environment: dev
      image: netex-photon-proxy:latest
      chart: helm/netex-photon-proxy
      namespace: netex-photon-proxy
